---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eda

resources:
  - github.com/ansible/eda-server-operator/config/default?ref=main
  - admin-password-secret.yaml

images:
  - name: quay.io/ansible/eda-server-operator
    newTag: main
